services:
  - type: web
    name: nature-care-impex
    env: node
    region: oregon
    plan: free
    autoDeploy: true
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_ATLAS_URI
        value: mongodb+srv://pavithra2282009_db_user:Pavi9876543210@cluster0.awahsjz.mongodb.net/nature_care_impex?retryWrites=true&w=majority&appName=Cluster0
      - key: OWNER_USERNAME
        value: admin
      - key: OWNER_PASSWORD
        value: 2025